apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: bsainiharika/flexr-app:backend-v6
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DATABASE_URL
            - name: SUPPORT_PHONE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SUPPORT_PHONE
            - name: SUPPORT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SUPPORT_EMAIL
          resources:
            requests:
              cpu: 50m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 128Mi
