apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  SUPPORT_PHONE: "+91 1800-200-3939"
  SUPPORT_EMAIL: "help@flexr.app"
  DATABASE_URL: "postgresql://flexr_user:change_me@db:5432/flexr"
  POSTGRES_USER: "flex_user"
  POSTGRES_DB: "flexr"

